changed trigger from feature to development

diff --git a/.github/workflows/Docker-CI.yml b/.github/workflows/Docker-CI.yml
--- a/.github/workflows/Docker-CI.yml
+++ b/.github/workflows/Docker-CI.yml
@@ -5,11 +5,15 @@ on:
       workflows: ["Terraform CICD"]
       types:
         - completed
-        
+
+  push: 
+     branches:
+      - development
 permissions:
      contents: read
      packages: write
      id-token: write
+     actions: read 
 
 jobs:
   build:
@@ -28,17 +32,25 @@ jobs:
       with:
          workflow: infra.yml
          name: terraform CICD
-         path: ./Infra-Terraform/terraform-output.json
+         path: ./Infra-Terraform
          run_id: ${{ github.events.workflow_run.id }}
-         
+         github_token: ${{ secrets.GITHUB_TOKEN }}
 
-    
     - name: List files in Infra-Terraform directory(degugging)
       run: ls -R ./Infra-Terraform
 
     - name: Parse ACR values from Terraform output
       id: tf
       run: |
+
+        # Ensure the file exists and is properly downloaded
+        if [[ ! -f ./Infra-Terraform/terraform-output.json ]]; then
+          echo "Terraform output file not found!"
+          exit 1
+        fi
+
+        # Extract the ACR login server, username, and password from the downloaded JSON
+
         ACR_LOGIN_SERVER=$(jq -r '.acr_login_server.value' Infra-Terraform/terraform-output.json)
         ACR_USERNAME=$(jq -r '.acr_username.value' Infra-Terraform/terraform-output.json)
         ACR_PASSWORD=$(jq -r '.acr_password.value' Infra-Terraform/terraform-output.json)
