modification

diff --git a/.github/workflows/Docker-CI.yml b/.github/workflows/Docker-CI.yml
--- a/.github/workflows/Docker-CI.yml
+++ b/.github/workflows/Docker-CI.yml
@@ -159,8 +159,27 @@ jobs:
       run: docker scan ${{ steps.meta.outputs.tags }}
       continue-on-error: true
 
-    - name: Upload ACR credentials as artifacts
-      uses: actions/upload-artifact@v4
+    - name: Download ACR credentials
+      uses: actions/download-artifact@v4
       with:
         name: acr-credentials
-        path: ./Infra-Terraform/terraform-output.json
+        path: ./downloaded-artifacts
+
+    - name: Parse ACR values from Terraform output
+      id: tf
+      run: |
+          # Ensure the terraform-output.json file exists
+          if [[ ! -f ./downloaded-artifacts/combined_artifacts/terraform-output.json ]]; then
+            echo "Terraform output file not found!"
+            exit 1
+          fi
+
+          # Extract the ACR login server, username, and password from the terraform output JSON
+          ACR_LOGIN_SERVER=$(jq -r '.acr_login_server.value' ./downloaded-artifacts/combined_artifacts/terraform-output.json)
+          ACR_USERNAME=$(jq -r '.acr_username.value' ./downloaded-artifacts/combined_artifacts/terraform-output.json)
+          ACR_PASSWORD=$(jq -r '.acr_password.value' ./downloaded-artifacts/combined_artifacts/terraform-output.json)
+
+          # Set the extracted values as outputs
+          echo "loginServer=$ACR_LOGIN_SERVER" >> $GITHUB_OUTPUT
+          echo "username=$ACR_USERNAME" >> $GITHUB_OUTPUT
+          echo "password=$ACR_PASSWORD" >> $GITHUB_OUTPUT
